apiVersion: v1
kind: Secret
metadata:
  name: my-ca-cert
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    konghq.com/ca-cert: 'true'
type: Opaque
stringData:
  cert: |
    -----BEGIN CERTIFICATE-----
    MIIFjjCCA3agAwIBAgIJALRfWCb1SN+hMA0GCSqGSIb3DQEBCwUAMFQxCzAJBgNV
    BAYTAldEMQ4wDAYDVQQIDAVFYXJ0aDEPMA0GA1UEBwwGR2xvYmFsMRIwEAYDVQQK
    DAlLb25nIEluYy4xEDAOBgNVBAMMB0tvbmcgQ0EwHhcNMjIwNjA2MTczMDE0WhcN
    NDIwNjAxMTczMDE0WjBUMQswCQYDVQQGEwJXRDEOMAwGA1UECAwFRWFydGgxDzAN
    BgNVBAcMBkdsb2JhbDESMBAGA1UECgwJS29uZyBJbmMuMRAwDgYDVQQDDAdLb25n
    IENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA6okM3maTTzQGelZh
    PyN5LWtJjvuatbYKyYQqQ7y3egH0VAFCntzGoenbj7mJKlHMCQWXyjGFGkVJZf4R
    M5TIMY/D52fnEKDcu0NQRVC447pE/2t29JOsqTUO3HfGd+8WLbQ2saniYJFhAthp
    jtMY8KGfpNmf00GsuyRow5E7h2/N/cNIvlyS2f0cKzPRdhMrQkWQbBAfMXHHtf/B
    C0ZGX1JBralgpP+Xw1fF0hVsFWWFlVqxRKvrZX9a32dpqxK907wsPxzu+fS+evwF
    fZdNMNSldfbUd9PAreAc5vwvqfU8dL/o2x+Ljjz9bw6JOG4ypYfPeELxtPnRJ9oG
    f4ODlvbPidZ+bAO/YtzAP/2g4WVlsXiASVXxiOpuheozw2OKsAvv/4bX17+WuVqP
    TO4swE+v1Y8tTB158LbWHkgPgHTdJQLCUq1xCE3fPr2qgn12c9tstPyxhEcNixR7
    Sjyy+vQZ80K33wL3AXHUuCxTk+8Z5vgWBBaFNTTnPcSYadZtMXu+1miXYwoyMACP
    2/NmUXTkA0WJBLnZtL6FWu/myeD0ijNMkCZupKrCpLaZho5LHACUj0MvWAN9Xy4N
    Law9/QcOUC6izU381wF4964RqxKsRZuWltwmchGicvwXxcTYkssyBdZgUDh4A36l
    2+UlvhkvXRp+6IbvBQN0tMNx82kCAwEAAaNjMGEwHQYDVR0OBBYEFGFhJey2KiWx
    QvyYP3C8ut8GESAFMB8GA1UdIwQYMBaAFGFhJey2KiWxQvyYP3C8ut8GESAFMA8G
    A1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGGMA0GCSqGSIb3DQEBCwUAA4IC
    AQCBtRnavwfg9ARHRc5T9+8yMkUkn3pZDKUX7ERkMRIPM/Hc2LBJ+n4K4tYKqKhZ
    H0ElaoOQGZUJmXvch+mYgcuf4+zEXEXYrezxHvaUnwcnneSLFgrHVVoi6YtUt2eD
    Fl+OxyCYKr+sn7SgUXAmJJWz662vnA1p38p0oakwuglezziiboaq/38JhvYfwjJK
    Z/HMMhISEH3uD+OBq/jZfREpnYRXa7F9ugocSA2nZRw0qyna7/vzwjxsEaNhmofK
    H/G09dNYFaS+WWfW0FQuZZsMFgC9HhAYE3rXw/3wDwqImBtXbru/7WpN0hc8Fe3L
    YqVHkz/TUJY1VNRQzInYbCiOs4+REo03kWYBahvW3vppVjJfSEHIIuVxZKG8NvsH
    YbbmpcIbLp27kAKj6IZMY/jiJmppFFfovHarEXNltcmrYVdaM2VrrFtGlm06H+xp
    B3c/n0kyY5VYIPX/0sgyl9xGAxBGiF32M6TKE+cSgX/oKF2Ie1TdqvsFKczzP2eG
    GUfI/bRDinyOEmoFNq43oHbwQc+TlBkKNiLQtcQ+Lkdi7ykBCrAqNg7vkXasu9pa
    bGn5Tg2iaD9h+/xZ6epakaiS5dFTaOFghZIxa91ZruQ4T+als+N696fCya1ZWxQ/
    dq1opnCj2Tx5zfcDw9St5vI1uRwMoe5z5sM4UrEd1VfnXQ==
    -----END CERTIFICATE-----
  id: cce8c384-721f-4f58-85dd-50834e3e733a