apiVersion: v1
kind: Secret
metadata:
  name: my-ca-cert
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    konghq.com/ca-cert: 'true'
type: Opaque
stringData:
  cert: |
    <replace with valid cert>
    -----END CERTIFICATE-----
  id: <generater a unique id similar to this cce8c384-721f-4f58-85dd-50834e3e733a>
