apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: mtls-auth
config:
  ca_certificates:
  - <replace with certificate id>
  skip_consumer_lookup: true
  revocation_check_mode: SKIP
plugin: mtls-auth
